### ISSUE TITLE
No 'version' key in the manifest

### ISSUE THREAD

**Issue by speharpre** [shamanenas/python-domintell#4]
I have noticed this in the logs. We are at version 2021.4, but as from 2021.6, this extension will no longer work : 

WARNING (MainThread) [homeassistant.loader] No 'version' key in the manifest file for custom integration 'domintell'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'domintell'

**Comment by zilvinasbin** [comment]
Thanks for pointing this

**Comment by zilvinasbin** [comment]
It applies to has_domintell, closing here. fixed in has_domintell

**Comment by speharpre** [comment]
Thank you so much.

Any plan to support the Domintell’s TRP modules ?


[WIZE]
Stéphane Péharpré
Managing Director
wize SRL
TEL: +32 475 60 50 35
Email: ***@***.******@***.***>
Web: www.wize.be



From: Zilvinas ***@***.***>
Date: Thursday, 22 April 2021 at 11:14
To: shamanenas/python-domintell ***@***.***>
Cc: Stephane Peharpre ***@***.***>, Author ***@***.***>
Subject: Re: [shamanenas/python-domintell] No 'version' key in the manifest (#4)

Closed #4<https://github.com/shamanenas/python-domintell/issues/4>.

**Comment by zilvinasbin** [comment]
> Any plan to support the Domintell’s TRP modules ? 

Hi DTRP01 is actually supported for ages. Just noticed that it's not included into readme:

The config for HomeAssistant shall be something like this:
```
switch: 
  - platform: domintell
    devices:
      - type: TRP 
        module: 850
        channel: 1
        name: Parents room sockets
        path: Namas|2nd Floor|Master Bedroom
      - type: TRP
        module: 850
        channel: 2
        name: Parents TV
        path: Namas|2nd Floor|Master Bedroom
      - type: TRP
        module: 850
        channel: 3
        name: Bathroom sockets
        path: Namas|2nd Floor|Bathroom
      - type: TRP
        module: 850
        channel: 4
        name: Kids PC
        path: Namas|2nd Floor|Bedroom
```
